services:
  - type: web
    name: hygiene-checker
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      PYTHON_VERSION: 3.11.8
